services:
  - type: web
    name: ratoffice
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: BAKONG_TOKEN
        sync: false
      - key: BACKEND_SECRET_KEY
        generateValue: true
      - key: MERCHANT_ACCOUNT
        value: chheak_narat@bkrt
      - key: MERCHANT_NAME
        value: NARAT CHHEAK
      - key: MERCHANT_CITY
        value: Phnom Penh
      - key: MERCHANT_PHONE
        value: ""
      - key: QR_EXPIRES_SECONDS
        value: "180"
      - key: CORS_ORIGINS
        value: http://localhost:5173,http://localhost:5174,https://ratoffice.vercel.app
